import Head from 'next/head';
import React from 'react';
import Navbar from './navbar';
import Footer from './footer';
export default function Layout1({ title = '小新的網站', children }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="container">{children}</div>
      <Footer />
    </>
  );
}
