import Head from 'next/head';
import React from 'react';
import Navbar from './navbar';
import Footer from './footer';

export default function layout({ title = '咖啡網站', children }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar />
      <div className="container">{children}</div>
      <Footer />
    </>
  );
}
