const products = [
  {
    p_id: '1',
    p_name: '祕魯 阿拉比卡 半日曬處理',
    p_price: '1910',
    p_discount: '1800',
    p_type: '咖啡豆',
    p_country: '瓜地馬拉',
    p_breed: '帝比卡',
    p_process: '半水洗處理',
    p_roast: '深烘焙',
    p_sale: '原價八折',
    p_date: '1995-03-14',
    p_stock: '43',
    p_sold: '67',
    p_pic: '/img/product7.jpg',
  },
  {
    p_id: '2',
    p_name: '哥斯大黎加 卡杜拉',
    p_price: '930',
    p_discount: '800',
    p_type: '推薦送禮',
    p_country: '台灣',
    p_breed: '藝妓',
    p_process: '水洗處理',
    p_roast: '中烘焙',
    p_sale: '原價八折',
    p_date: '1989-01-20',
    p_stock: '54',
    p_sold: '51',
    p_pic: '/img/product2.jpg',
  },
  {
    p_id: '3',
    p_name: '衣索比亞 卡杜拉',
    p_price: '1050',
    p_discount: '950',
    p_type: '咖啡豆',
    p_country: '巴拿馬',
    p_breed: '帝比卡',
    p_process: '葡萄乾蜜處理',
    p_roast: '中烘焙',
    p_sale: '原價八折',
    p_date: '1987-08-13',
    p_stock: '53',
    p_sold: '99',
    p_pic: '/img/product5.jpg',
  },
  {
    p_id: '4',
    p_name: '台灣 卡杜拉 半日曬處理',
    p_price: '890',
    p_discount: '790',
    p_type: '季節限定',
    p_country: '哥倫比亞',
    p_breed: '藝妓',
    p_process: '葡萄乾蜜處理',
    p_roast: '淺烘焙',
    p_sale: '原價八折',
    p_date: '1989-04-28',
    p_stock: '78',
    p_sold: '42',
    p_pic: '/img/product13.jpg',
  },
  {
    p_id: '5',
    p_name: '台灣 藝妓 葡萄乾蜜處理',
    p_price: '410',
    p_discount: '300',
    p_type: '推薦送禮',
    p_country: '巴西',
    p_breed: '阿拉比卡',
    p_process: '半日曬處理',
    p_roast: '淺烘焙',
    p_sale: '原價八折',
    p_date: '1998-12-01',
    p_stock: '32',
    p_sold: '92',
    p_pic: '/img/product5.jpg',
  },
  {
    p_id: '6',
    p_name: '巴西 卡杜拉 半水洗處理',
    p_price: '1770',
    p_discount: '1700',
    p_type: '咖啡豆',
    p_country: '瓜地馬拉',
    p_breed: '卡杜拉',
    p_process: '半日曬處理',
    p_roast: '淺烘焙',
    p_sale: '原價八折',
    p_date: '1991-09-22',
    p_stock: '49',
    p_sold: '51',
    p_pic: '/img/product5.jpg',
  },
  {
    p_id: '7',
    p_name: '哥倫比亞 帝比卡 半水洗',
    p_price: '2840',
    p_discount: '2600',
    p_type: '咖啡豆',
    p_country: '衣索比亞',
    p_breed: '帝比卡',
    p_process: '半日曬處理',
    p_roast: '淺烘焙',
    p_sale: '原價八折',
    p_date: '1997-01-06',
    p_stock: '73',
    p_sold: '92',
    p_pic: '/img/product6.jpg',
  },
  {
    p_id: '8',
    p_name: '哥斯大黎加 帝比卡',
    p_price: '3130',
    p_discount: '2504',
    p_type: '推薦送禮',
    p_country: '瓜地馬拉',
    p_breed: '卡杜拉',
    p_process: '水洗處理',
    p_roast: '深烘焙',
    p_sale: '原價八折',
    p_date: '1995-03-25',
    p_stock: '87',
    p_sold: '74',
    p_pic: '/img/product9.jpg',
  },
  {
    p_id: '10',
    p_name: '台灣 卡杜拉 半日曬處理',
    p_price: '2970',
    p_discount: '2760',
    p_type: '推薦送禮',
    p_country: '哥倫比亞',
    p_breed: '阿拉比卡',
    p_process: '半水洗處理',
    p_roast: '深烘焙',
    p_sale: '原價八折',
    p_date: '1989-08-22',
    p_stock: '99',
    p_sold: '98',
    p_pic: '/img/product5.jpg',
  },
]

export default products
